# Generated by Django 4.0.4 on 2022-06-04 12:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0015_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.IntegerField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
