# Generated by Django 4.0.5 on 2022-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_review_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
