# Generated by Django 4.0.5 on 2022-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_alter_course_price_alter_review_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
