# Generated by Django 4.0.4 on 2022-06-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=2, help_text='the product rating from 0 - 10', max_digits=2),
        ),
    ]
