# Generated by Django 4.0.4 on 2022-06-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=0, help_text='the product rating from 0 - 10', max_digits=3),
        ),
    ]
